### ISSUE TITLE
Package uses wrong vendor name

### ISSUE THREAD

**Issue by localheinz** [structurizr-php/extensions-php#2]
Looks like the vendor name is wrong, see https://packagist.org/packages/struturizr-php/extensions-php:

<img width="1195" alt="Screen Shot 2019-12-11 at 09 32 18" src="https://user-images.githubusercontent.com/605483/70604591-2df41900-1bf9-11ea-9017-7c6398f34f83.png">

**Comment by norberttech** [comment]
typos everywhere 🤦‍♂ Thanks! Will fix that once I get to the office

**Comment by localheinz** [comment]
@norzechowicz 

No problem, happens to all of us!

:wink
